'use strict';
const el=id=>document.getElementById(id),frame=el('game');let bridge,catalog,skillSignature='',lastMessage='';
const say=m=>{el('log').textContent=String(m)+'\n'+el('log').textContent.slice(0,1500);};
const call=(fn,...args)=>{try{const result=bridge[fn](...args);refresh();return result;}catch(e){say(e.message);}};
const fill=(id,list)=>{el(id).replaceChildren(...list.map(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name+' · '+x.id;return o;}));};
for(const [i,name] of ['E','SE','S','SW','W','NW','N','NE'].entries()){const o=document.createElement('option');o.value=i;o.textContent=name;el('direction').append(o);}el('direction').value=2;
for(const key of ['str','agi','vit','int','dex','luk']){const l=document.createElement('label');l.textContent=key.toUpperCase();const input=document.createElement('input');input.id=key;input.type='number';input.min=1;input.max=99;input.value=20;l.append(input);el('stats').append(l);}
const options=()=>call('options',Object.fromEntries(['noCooldown','infinite','invincible','paused','sound'].map(id=>[id,el(id).checked]).concat([['speed',el('speed').value],['quality',el('quality').value],['scene',el('scene').value]])));
for(const id of ['noCooldown','infinite','invincible','paused','sound','speed','quality','scene'])el(id).onchange=options;
const sync=s=>{for(const id of ['baseLv','jobLv','zeny'])el(id).value=s[id];for(const k of Object.keys(s.stats))el(k).value=s.stats[k];};

const familyLabels={novice:'เริ่มต้น',einherjar:'นักรบ',wildhunter:'นักธนู',runecaster:'วิทยาศาสตร์',volva:'แพทย์ / สนับสนุน',trickster:'จู่โจม',berserker:'เบอร์เซิร์ก'};
function rootOf(job){let j=catalog.jobs.find(x=>x.id===job);const seen=new Set();while(j?.parent&&!seen.has(j.id)){seen.add(j.id);j=catalog.jobs.find(x=>x.id===j.parent)||j;}return j?.id||job;}
function chooseJob(job){if(!bridge)return;el('job').value=job;const s=call('build',job,el('gender').value);if(s){sync(s);el('pose').value='live';call('pose','live',el('direction').value);}}
function renderClasses(s){const root=rootOf(s.job);for(const button of el('families').querySelectorAll('button')){const on=button.dataset.root===root;button.classList.toggle('selected',on);button.setAttribute('aria-pressed',String(on));}
 const current=el('class-jobs').dataset.root;if(current!==root){el('class-jobs').dataset.root=root;el('class-jobs').replaceChildren();for(const j of catalog.jobs.filter(x=>rootOf(x.id)===root).sort((a,b)=>a.tier-b.tier)){const button=document.createElement('button');button.dataset.job=j.id;const tier=document.createElement('small');tier.textContent=j.tier?'Class '+j.tier:'เริ่มต้น';button.append(tier,document.createTextNode(j.name));button.onclick=()=>chooseJob(j.id);el('class-jobs').append(button);}}
 for(const button of el('class-jobs').querySelectorAll('button')){const on=button.dataset.job===s.job;button.classList.toggle('selected',on);button.setAttribute('aria-pressed',String(on));}
 const j=catalog.jobs.find(x=>x.id===s.job);el('selected-job').textContent=j?.name||s.job;el('current-class').textContent=(j?.name||s.job)+' / '+(s.gender==='f'?'หญิง':'ชาย');el('job').value=s.job;
}
function refresh(){if(!bridge||!catalog)return;const s=bridge.state();renderClasses(s);const msg=bridge.messages().at(-1);if(msg&&msg!==lastMessage){say(msg);lastMessage=msg;}
 el('metrics').textContent=`Base ${s.baseLv} / Job ${s.jobLv} • HP ${Math.round(s.hp)}/${s.maxHp} • SP ${Math.round(s.sp)}/${s.maxSp} • เป้า ${s.targetHP===null?'—':Math.round(s.targetHP)} • ยูนิต ${s.allies} • ${s.cast?'กำลังใช้ '+s.cast:s.paused?'หยุดจำลอง':'พร้อม'}`;
 el('equipment').textContent=Object.entries(s.equipment).map(([k,v])=>k+': '+(v||'—')).join(' | ');
 for(const sk of s.skills){const text=el('skills').querySelector(`[data-skill="${sk.id}"] .cooldown`);if(text){text.textContent=s.noCooldown?'กดใช้':sk.cooldown>.05?sk.cooldown.toFixed(1)+'s':'พร้อม';text.closest('button').classList.toggle('on-cooldown',!s.noCooldown&&sk.cooldown>.05);}}
 const signature=JSON.stringify([s.job,s.gender,s.skills.map(x=>[x.id,x.lv,x.rune,x.icon]),el('skill-search').value,el('skill-scope').value,s.noCooldown]);if(signature===skillSignature)return;if(document.activeElement?.matches('.feedback textarea'))return;skillSignature=signature;
 el('skills').replaceChildren();el('passive-skills').replaceChildren();const q=el('skill-search').value.toLowerCase();const shown=s.skills.filter(x=>el('skill-scope').value==='line'||x.current);el('passive-count').textContent='('+shown.filter(x=>x.type==='passive').length+')';el('skill-count').textContent=shown.filter(x=>x.type==='active').length+' Active / '+shown.filter(x=>x.type==='passive').length+' Passive • ไม่มีคูลดาวน์: '+(s.noCooldown?'เปิด':'ปิด');const groups={active:null,passive:null};
 for(const sk of shown.filter(x=>(x.name+' '+x.id).toLowerCase().includes(q)).sort((a,b)=>Number(b.current)-Number(a.current)||a.owner.localeCompare(b.owner))){const active=sk.type==='active',card=document.createElement('div');card.className='skill';card.dataset.skill=sk.id;const group=active?'active':'passive';if(groups[group]!==sk.owner){groups[group]=sk.owner;const heading=document.createElement('div');heading.className='skill-group';heading.dataset.owner=sk.owner;heading.textContent=catalog.jobs.find(j=>j.id===sk.owner)?.name||sk.owner;el(active?'skills':'passive-skills').append(heading);}
  const button=document.createElement(active?'button':'div');button.className='skill-cast';
  if(sk.icon){const img=document.createElement('img');img.src=sk.icon;img.alt='';button.append(img);}else{const icon=document.createElement('span');icon.className='icon-fallback';icon.textContent=sk.name.slice(0,1);button.append(icon);}
  const title=document.createElement('span');title.className='skill-title';title.textContent=sk.name;const detail=document.createElement('small');detail.textContent=(active?'Lv ':'Passive Lv ')+sk.lv+'/'+sk.max+(!sk.current?' · สืบทอด':'');title.append(detail);button.append(title);
  if(active){button.setAttribute('aria-label','ใช้ '+sk.name);const cd=document.createElement('span');cd.className='cooldown';cd.textContent=s.noCooldown?'กดใช้':sk.cooldown>.05?sk.cooldown.toFixed(1)+'s':'พร้อม';button.append(cd);button.onclick=()=>{call('cast',sk.id,sk.lv);el('pose').value='live';};}card.append(button);
  const settings=document.createElement('details'),summary=document.createElement('summary');summary.textContent='ระดับ / ปรับสกิล';settings.append(summary);
  const label=document.createElement('label');label.textContent='ระดับสกิล';const lv=document.createElement('input');lv.type='number';lv.min=active?1:0;lv.max=sk.max;lv.value=sk.lv;lv.setAttribute('aria-label','ระดับ '+sk.name);lv.onchange=()=>call('level',sk.id,lv.value);label.append(lv);settings.append(label);
  if(sk.runes.length){const select=document.createElement('select');select.setAttribute('aria-label','ปรับ '+sk.name);const none=document.createElement('option');none.value='';none.textContent='ไม่เลือกการปรับสกิล';select.append(none);for(const r of sk.runes){const opt=document.createElement('option');opt.value=r.id;opt.textContent=r.name;select.append(opt);}select.value=sk.rune||'';select.onchange=()=>call('rune',sk.id,select.value);settings.append(select);}card.append(settings);appendFeedback(card,s,sk);el(active?'skills':'passive-skills').append(card);
 }
}
el('skill-search').oninput=refresh;el('skill-scope').onchange=refresh;
el('job').onchange=()=>chooseJob(el('job').value);el('gender').onchange=()=>chooseJob(el('job').value);
for(const id of ['pose','direction'])el(id).onchange=()=>call('pose',el('pose').value,el('direction').value);
el('numbers').onclick=()=>{const s=call('numbers',Object.fromEntries(['baseLv','jobLv','zeny','str','agi','vit','int','dex','luk'].map(id=>[id,el(id).value])));if(s)sync(s);};
for(const id of ['target','clear','heal'])el(id).onclick=()=>call(id);
el('item-search').oninput=()=>fill('item',catalog.items.filter(x=>(x.name+' '+x.id).toLowerCase().includes(el('item-search').value.toLowerCase())));
el('add-item').onclick=()=>call('item',el('item').value,el('qty').value,false);el('equip-item').onclick=()=>call('item',el('item').value,el('qty').value,true);el('unequip').onclick=()=>call('unequip',el('slot').value);
el('warp').onclick=()=>call('command','/gm warp '+el('map').value);el('spawn').onclick=()=>call('command','/gm spawn '+el('mob').value+' 1');el('run').onclick=()=>{call('command',el('command').value);say(el('command').value);};
el('viewport').onchange=()=>frame.classList.toggle('portrait',el('viewport').value==='portrait');el('fullscreen').onclick=()=>el('battle').requestFullscreen().catch(e=>say(e.message));
const FEEDBACK_KEY='nm_character_lab_feedback_v1';
let feedback={};try{feedback=JSON.parse(localStorage.getItem(FEEDBACK_KEY)||'{}');if(!feedback||typeof feedback!=='object'||Array.isArray(feedback))feedback={};}catch(e){feedback={};}
function appendFeedback(card,state,skill){const key=state.job+':'+state.gender+':'+skill.id;const details=document.createElement('details');details.className='feedback';const summary=document.createElement('summary');summary.textContent=feedback[key]?.note?'คอมเมนต์ • บันทึกแล้ว':'คอมเมนต์สกิล';const input=document.createElement('textarea');input.placeholder='เช่น ท่าโจมตี / เอฟเฟกต์ / ลูกกระสุน / จุดที่ต้องแก้';input.maxLength=10000;input.setAttribute('aria-label','คอมเมนต์ '+skill.name);input.value=feedback[key]?.note||'';const status=document.createElement('small');status.className='note';status.textContent='เก็บในเครื่อง แยกอาชีพ / เพศ / สกิล';input.oninput=()=>{feedback[key]={job:state.job,gender:state.gender,skill:skill.id,owner:skill.owner,jobName:catalog.jobs.find(j=>j.id===state.job)?.name||state.job,skillName:skill.name,note:input.value,updatedAt:new Date().toISOString()};try{localStorage.setItem(FEEDBACK_KEY,JSON.stringify(feedback));status.textContent='บันทึกคอมเมนต์ในเครื่องแล้ว';summary.textContent=input.value?'คอมเมนต์ • บันทึกแล้ว':'คอมเมนต์สกิล';}catch(e){status.textContent='บันทึกไม่สำเร็จ — ดาวน์โหลดคอมเมนต์เก็บไว้';}};details.append(summary,input,status);card.append(details);}
el('export-feedback').onclick=()=>{const rows=Object.values(feedback).filter(x=>x.note?.trim());const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,kind:'character-lab-feedback',comments:rows},null,2)],{type:'application/json'}));download(url,'character-lab-feedback.json');setTimeout(()=>URL.revokeObjectURL(url),1000);};
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();}
el('export').onclick=()=>{const data=call('export');if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));download(url,'character-lab.json');setTimeout(()=>URL.revokeObjectURL(url),1000);};
el('capture').onclick=()=>{const url=call('screenshot');if(url)download(url,'character-lab.png');};el('reset').onclick=()=>location.reload();
async function start(){if(!['localhost','127.0.0.1','[::1]'].includes(location.hostname)){el('status').textContent='ใช้ได้บน localhost เท่านั้น';return;}document.querySelectorAll('button').forEach(b=>b.disabled=true);frame.src='index.html?local-test=1&character-lab=1';const deadline=Date.now()+90000;while(Date.now()<deadline){bridge=frame.contentWindow.CharacterLabBridge;if(bridge)break;await new Promise(r=>setTimeout(r,150));}if(!bridge){el('status').textContent='โหลดไม่สำเร็จ';say('ไม่พบระบบทดสอบ ลองรีโหลดหน้า');return;}catalog=bridge.catalog();fill('job',catalog.jobs.map(j=>({...j,name:'C'+j.tier+' '+j.name})));for(const root of catalog.jobs.filter(j=>!j.parent)){const button=document.createElement('button');button.dataset.root=root.id;button.textContent=familyLabels[root.id]||root.name;button.onclick=()=>chooseJob(root.id);el('families').append(button);}fill('item',catalog.items);fill('mob',catalog.mobs);fill('map',catalog.maps);fill('slot',Object.keys(bridge.state().equipment).map(id=>({id,name:id})));el('help').textContent=catalog.commands.join('\n');document.querySelectorAll('button').forEach(b=>b.disabled=false);el('status').textContent='LOCAL • เซฟชั่วคราว';sync(bridge.state());options();refresh();setInterval(refresh,250);}
start().catch(e=>{el('status').textContent='โหลดไม่สำเร็จ';say(e.message);});
